#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : qtx11extras
Version  : 5.11.2
Release  : 11
URL      : http://download.qt.io/official_releases/qt/5.11/5.11.2/submodules/qtx11extras-everywhere-src-5.11.2.zip
Source0  : http://download.qt.io/official_releases/qt/5.11/5.11.2/submodules/qtx11extras-everywhere-src-5.11.2.zip
Summary  : No detailed summary available
Group    : Development/Tools
License  : GFDL-1.3 GPL-2.0 GPL-3.0 LGPL-3.0
Requires: qtx11extras-lib
Requires: qtx11extras-license
BuildRequires : buildreq-cmake
BuildRequires : buildreq-qmake
BuildRequires : mesa-dev
BuildRequires : pkgconfig(Qt5Gui)
BuildRequires : pkgconfig(Qt5Test)
BuildRequires : pkgconfig(Qt5Widgets)
BuildRequires : pkgconfig(xcb)

%description
No detailed description available

%package dev
Summary: dev components for the qtx11extras package.
Group: Development
Requires: qtx11extras-lib = %{version}-%{release}
Provides: qtx11extras-devel = %{version}-%{release}

%description dev
dev components for the qtx11extras package.


%package lib
Summary: lib components for the qtx11extras package.
Group: Libraries
Requires: qtx11extras-license = %{version}-%{release}

%description lib
lib components for the qtx11extras package.


%package license
Summary: license components for the qtx11extras package.
Group: Default

%description license
license components for the qtx11extras package.


%prep
%setup -q -n qtx11extras-everywhere-src-5.11.2

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
%qmake
test -r config.log && cat config.log
make  %{?_smp_mflags}

%install
export SOURCE_DATE_EPOCH=1537312835
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/doc/qtx11extras
cp LICENSE.FDL %{buildroot}/usr/share/doc/qtx11extras/LICENSE.FDL
cp LICENSE.GPL2 %{buildroot}/usr/share/doc/qtx11extras/LICENSE.GPL2
cp LICENSE.GPL3 %{buildroot}/usr/share/doc/qtx11extras/LICENSE.GPL3
cp LICENSE.GPL3-EXCEPT %{buildroot}/usr/share/doc/qtx11extras/LICENSE.GPL3-EXCEPT
cp LICENSE.LGPL3 %{buildroot}/usr/share/doc/qtx11extras/LICENSE.LGPL3
%make_install

%files
%defattr(-,root,root,-)

%files dev
%defattr(-,root,root,-)
/usr/include/qt5/QtX11Extras/QX11Info
/usr/include/qt5/QtX11Extras/QtX11Extras
/usr/include/qt5/QtX11Extras/QtX11ExtrasDepends
/usr/include/qt5/QtX11Extras/QtX11ExtrasVersion
/usr/include/qt5/QtX11Extras/qtx11extrasglobal.h
/usr/include/qt5/QtX11Extras/qtx11extrasversion.h
/usr/include/qt5/QtX11Extras/qx11info_x11.h
/usr/lib64/cmake/Qt5X11Extras/Qt5X11ExtrasConfig.cmake
/usr/lib64/cmake/Qt5X11Extras/Qt5X11ExtrasConfigVersion.cmake
/usr/lib64/libQt5X11Extras.prl
/usr/lib64/libQt5X11Extras.so
/usr/lib64/pkgconfig/Qt5X11Extras.pc
/usr/lib64/qt5/mkspecs/modules/qt_lib_x11extras.pri
/usr/lib64/qt5/mkspecs/modules/qt_lib_x11extras_private.pri

%files lib
%defattr(-,root,root,-)
/usr/lib64/libQt5X11Extras.so.5
/usr/lib64/libQt5X11Extras.so.5.11
/usr/lib64/libQt5X11Extras.so.5.11.2

%files license
%defattr(-,root,root,-)
/usr/share/doc/qtx11extras/LICENSE.FDL
/usr/share/doc/qtx11extras/LICENSE.GPL2
/usr/share/doc/qtx11extras/LICENSE.GPL3
/usr/share/doc/qtx11extras/LICENSE.GPL3-EXCEPT
/usr/share/doc/qtx11extras/LICENSE.LGPL3
